/**
 * Bundles data/puzzles.mjs into public/pack.js as base64.
 * Run via `npm run build`. The output is generated — never edit it by hand.
 */
import fs from "node:fs";
import path from "node:path";
import puzzles from "../data/puzzles.mjs";

const json = JSON.stringify(puzzles);
const encoded = Buffer.from(json, "utf8").toString("base64");
const out = path.resolve("public/pack.js");

fs.writeFileSync(
  out,
  `// Generated by scripts/build-pack.mjs — do not edit.\n` +
    `// ${puzzles.length} puzzles, built ${new Date().toISOString()}\n` +
    `export const PACK = "${encoded}";\n`
);

const kb = (Buffer.byteLength(encoded) / 1024).toFixed(1);
console.log(`✓ packed ${puzzles.length} puzzles → public/pack.js (${kb} kB)`);
